#!/bin/bash
clear
cd /Volumes/PhotoSSD/WEBSITE_Pandaatje/Website/images/
echo "Creating data for:"
ls *.jpg

echo "---------------------------------------------"

# Example:
# {'file' : "DSC01449.jpg", 'name' : "XXX, XXX", 'format' : 'portrait'},
# {'file' : "DSC01449.jpg", 'name' : "XXX, XXX", 'format' : 'landscape'},

touch new_data.js

for i in $(ls *.jpg); do

    w=$(identify -format "%w" $i)
    h=$(identify -format "%h" $i)

    filename="${i%.*}"
    echo "$filename"

    if [[ $w > $h ]];then
        echo "{'file' : '$filename', 'name' : '000 - Title - Location, Country', 'format' : 'L'}," >> new_data.js
    else
        echo "{'file' : '$filename', 'name' : '000 - Title - Location, Country', 'format' : 'P'}," >> new_data.js
    fi

done
